---
title: "Descriptive Analysis for Cycle Sensor Data"
author: "Myeong Lee"
date: "6/27/2017"
output: html_document
---

```{r}
library(jsonlite)
library(readr)
library(dplyr)
library(sp)
library(ggplot2)
library(ggmap)
library(dplyr)
library(tidyr)
library(geosphere)

setwd("/Users/myeong/git/Atl_DSSG/Cycle-Atlanta-SLaB/DSSG2017_data/sample_data/")

gps <- fromJSON(txt= "Jeremy/140717_gps_data.json" )
gps <- as.data.frame(gps["results"])
colnames(gps) <- c("lon", "course","lat","speed","day","utc_time")
gps$utc_time <- as.numeric(gps$utc_time)
gps$utc_time <- gps$utc_time - 40000
gps$utc_time <- as.character(gps$utc_time)


gps <- gps %>% separate(lon, into = c("dd","mm"), sep=3 )
gps$lon <- -(as.numeric(gps$dd) + (as.numeric(gps$mm)/60))
gps <- gps %>% separate(lat, into = c("dd2","mm2"), sep=2 )
gps$lat <- (as.numeric(gps$dd2) + (as.numeric(gps$mm2)/60))
gps <- gps[,c("course", "speed", "day", "utc_time", "lon", "lat")]

gps$speed <- as.numeric(gps$speed)
gps$course <- as.numeric(gps$course)

gps$seq <- c(1:nrow(gps))
gps[is.na(gps$lon),]$lon <- 0
gps[is.na(gps$lat),]$lat <- 0

gps_points <- SpatialPointsDataFrame(coords = gps[,c("lon","lat")], data = gps,
                               proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))

plot(gps_points)

map <- get_map(c(lon = -84.397, lat = 33.780), zoom = 15, source = "stamen", maptype = "toner")
mapPoints <- ggmap(map) + geom_point(aes(x = lon, y = lat), data = gps, alpha = .5, color="darkred", size = 1)
mapPoints

gps$speed <- gps$speed * 1.15078 # changing Knots to Miles/h
gps$way <- "On the way school"
gps[1:500,]$way <- "On the way home"
gps$way <- as.factor(gps$way)

#Speed

ggplot(gps, aes(x = seq, y = speed, colour=(way), group = 1)) +
  geom_line() +
  geom_point(size = 1) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="MPH") + 
  xlab("Time (sec)")  + ggtitle("Time-Series of Jeremy's Commuting Speed (July 14, 2017)")


# saving only coordinates as a right format
coord <- gps[,c("lat","lon")]
write.table(coord,file = "coord.csv", row.names=F, col.names=T, sep=",")

# Combining elevation data
elevation <- fromJSON(txt= "Jeremy/elevation.json" )
elevation$lat <- elevation$location$lat
elevation$lon <- elevation$location$lng
elevation <- elevation[,c("ID", "elevation")]

gps$ID <- c(1:nrow(gps))
elevation$ID <- elevation$ID + 1
gps <- gps %>% left_join(elevation, by=c("ID"))
gps[is.na(gps$elevation),]$elevation <- mean(gps$elevation, na.rm = T)
gps$slope <- 0

i=1

for (i in c(1:nrow(gps))){
  if (i ==1 ) {
    next
  }
  dist <- distm (c(gps[i-1,]$lon, gps[i-1,]$lat), c(gps[i,]$lon, gps[i,]$lat), fun = distHaversine)
  if (gps[i,]$elevation > gps[i-1,]$elevation) {
    gps[i,]$slope <- sqrt((gps[i,]$elevation - gps[i-1,]$elevation)^2 + dist^2)
  } else {
    gps[i,]$slope <- -sqrt((gps[i,]$elevation - gps[i-1,]$elevation)^2 + dist^2)
  }
  
}

gps[abs(gps$slope) > 10,]$slope <- 0
gps$Legend <- gps$way

ggplot(gps, aes(x = seq, y = speed, colour=Legend)) +
#   geom_line() +
#   geom_point(size = 1) +
  geom_smooth(method = "loess",span = 0.1) +
  geom_line(aes(y=scale(elevation), color="Elevation (relative)")) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="MPH") + 
  xlab("Dummy Time (sec)")  + ggtitle("Time-Series Speed of Jeremy's Commuting (July 14, 2017)")



```


# 7/19/2017 Javier's
```{r}
gps <- read_delim("signatures/go_as_fast_as_possible/fast_as_possilbe_GPS.csv", delim = ",", col_names = T)

colnames(gps) <- c("ID", "lon", "course","lat","speed","day","utc_time")
gps$utc_time <- as.integer(gps$utc_time)
gps$utc_time <- gps$utc_time - 40000
gps$utc_time <- as.character(gps$utc_time)
gps["utc_time"] <- as.POSIXct(gps$utc_time, origin="1970-01-01", format = "%H%M%S")

gps <- gps %>% separate(lon, into = c("dd","mm"), sep=2 )
gps$lon <- -(as.numeric(gps$dd) + (as.numeric(gps$mm)/60))
gps <- gps %>% separate(lat, into = c("dd2","mm2"), sep=2 )
gps$lat <- (as.numeric(gps$dd2) + (as.numeric(gps$mm2)/60))
gps <- gps[,c("course", "speed", "day", "utc_time", "lon", "lat")]

gps$speed <- as.numeric(gps$speed)
gps$course <- as.numeric(gps$course)

gps$seq <- c(1:nrow(gps))
gps[is.na(gps$lon),]$lon <- 0
gps[is.na(gps$lat),]$lat <- 0

# gps_points <- SpatialPointsDataFrame(coords = gps[,c("lon","lat")], data = gps,
#                                proj4string = CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"))
# 
# plot(gps_points)

gps$way <- "come"
gps[c(1:1468),]$way <- "go"
gps$way <- as.factor(gps$way)

map <- get_map(c(lon = -84.397, lat = 33.760), zoom = 14, source = "stamen", maptype = "toner")
mapPoints <- ggmap(map) + geom_point(aes(x = lon, y = lat, colour=way, size = (speed^2)/100), data = gps, alpha = 0.10) + labs(colour="Way", size="Speed")
mapPoints


map <- get_map(c(lon = -84.392, lat = 33.763), zoom = 17, source = "stamen", maptype = "toner")
mapPoints <- ggmap(map) +geom_point(aes(x = lon, y = lat, colour=way), data = gps[654:654,], alpha = 0.8, size = 0.5)
mapPoints

# 654 is the reference point to sync between GoPro video and the GPS data
gps$video_time <- as.POSIXct("00:07:20", origin="1970-01-01", format = "%H:%M:%S")

for (i in c(1:nrow(gps))){
  gps[i,]$video_time <- gps[654,]$video_time - 654 + i
}

# joining proximiyt values
prox <- read_delim("signatures/go_as_fast_as_possible/proximity_190717.csv", delim = ",", col_names = T)
prox$TimeN <- prox$TimeN - 40000
prox$TimeN <- as.character(prox$TimeN)
prox["time"] <- as.POSIXct(prox$TimeN, origin="1970-01-01", format = "%H%M%S")
prox_sum <- prox %>% dplyr::group_by(time) %>% summarise(USRight=mean(USRight),USLeft=mean(USLeft),USRear=mean(USRear),LidarRight=mean(LidarRight),LidarLeft=mean(LidarLeft),CO=mean(CO, na.rm=T),SO=mean(SO, na.rm=T),O3=mean(O3, na.rm=T),NO=mean(NO, na.rm=T),P10=mean(P10, na.rm=T),P25=mean(P25, na.rm=T))

gps <- gps %>% left_join(prox_sum, by=c("utc_time" = "time"))
write.table(gps, "signatures/go_as_fast_as_possible/prox_gps_join.csv", row.names=F, col.names=T, sep=",")

```


# Signatures
```{r}
gps <- read_delim("signatures/go_as_fast_as_possible/prox_gps_join.csv", delim = ",", col_names = T)
prox <- read_delim("signatures/go_as_fast_as_possible/proximity_190717.csv", delim = ",", col_names = T)
prox$TimeN <- prox$TimeN - 40000
prox$TimeN <- as.character(prox$TimeN)
prox["time"] <- as.POSIXct(prox$TimeN, origin="1970-01-01", format = "%H%M%S", tz = "UTC")


library(lubridate)
gps <- gps[,c("utc_time", "lon", "lat", "video_time", "course", "speed")]
gps$video_hour <- hour(ymd_hms(gps$video_time))
gps$video_minute <- minute(ymd_hms(gps$video_time))
gps$video_sec <- second(ymd_hms(gps$video_time))

prox <- prox[,c("time", "USRight", "USLeft", "USRear", "LidarRight", "LidarLeft", "sequenceTime")]
prox_join <- prox %>% left_join(gps, by=c("time"="utc_time"))

street_parking <- prox_join[prox_join$video_hour == 0 & ((prox_join$video_minute == 10 & prox_join$video_sec >= 57) | (prox_join$video_minute == 11 & prox_join$video_sec <= 3)),]
street_parking$sequenceTime <- c(1:nrow(street_parking))

street_parking_sig <- as.data.frame(matrix(ncol = 3, nrow = 0))
colnames(street_parking_sig) <- c("sequenceTime", "sensor", "value")

for (col in c("LidarRight", "LidarLeft")){
  tmp <- cbind(street_parking[,c("sequenceTime")], col, street_parking[,col])
  colnames(tmp) <- c("sequenceTime", "sensor", "value")
  street_parking_sig <- rbind(street_parking_sig, tmp)
}

street_parking_sig$sensor <- as.factor(street_parking_sig$sensor)
street_parking_sig$seq <- c(1:nrow(street_parking_sig))

library(dtt)
freq <- dtt(street_parking_sig[c(26:50),]$value, type = c("dct"))
freq <- as.data.frame(freq)
freq$index <- c(1:nrow(freq))

ggplot(freq, aes(x = index, y = abs(freq))) +
  geom_line() +
  geom_point(size = 1) +  ylim(c(0, 15000)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Amplitude") + 
  xlab("Frequency")  + ggtitle("Discrete Cosine Transform for the Street Parking Signature") 

ggplot(street_parking_sig, aes(x = seq, y = scale(value), colour = sensor)) +
  geom_line() +
  geom_point(size = 1) + 
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Normalized Distance") + 
  xlab("Time")  + ggtitle("Street Parking Temporal Signature") + labs(colour="Sensors") 
  


# Passing vehicle signature
passing_vehicle <- prox_join[prox_join$video_hour == 0 & ((prox_join$video_minute == 8 & prox_join$video_sec >= 49) & (prox_join$video_minute == 8 & prox_join$video_sec <= 55)),]
passing_vehicle$sequenceTime <- c(1:nrow(passing_vehicle))

passing_vehicle_sig <- as.data.frame(matrix(ncol = 3, nrow = 0))
colnames(passing_vehicle_sig) <- c("sequenceTime", "sensor", "value")

for (col in c("LidarRight", "LidarLeft")){
  tmp <- cbind(passing_vehicle[,c("sequenceTime")], col, passing_vehicle[,col])
  colnames(tmp) <- c("sequenceTime", "sensor", "value")
  passing_vehicle_sig <- rbind(passing_vehicle_sig, tmp)
}

passing_vehicle_sig$sensor <- as.factor(passing_vehicle_sig$sensor)
passing_vehicle_sig$seq <- c(1:nrow(passing_vehicle_sig))

freq <- dtt(passing_vehicle_sig[c(26:50),]$value, type = c("dct"))
freq <- as.data.frame(freq)
freq$index <- c(1:nrow(freq))


ggplot(freq, aes(x = index, y = abs(freq))) +
  geom_line() +
  geom_point(size = 1) +   ylim(c(0, 15000)) +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Amplitude") + 
  xlab("Frequency")  + ggtitle("Discrete Cosine Transform for the Passing Vehicle Signature") 

ggplot(passing_vehicle_sig, aes(x = seq, y = scale(value), colour = sensor)) +
  geom_line() +
  geom_point(size = 1) +  
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Normalized Distance") + 
  xlab("Time")  + ggtitle("Passing Vehicle Temporal Signature") + labs(colour="Sensors") 


```


# 7/20/2017 Noel's
```{r}
gps <- read_delim("signatures/Noel/170720_gps_noel.csv", delim = ",", col_names = T)

colnames(gps) <- c("lon", "course","lat","speed","day","utc_time", "Time")
gps$Time <- gps$Time - (3600 * 4)

gps <- gps %>% separate(lon, into = c("dd","mm"), sep=2 )
gps$lon <- -(as.numeric(gps$dd) + (as.numeric(gps$mm)/60))
gps <- gps %>% separate(lat, into = c("dd2","mm2"), sep=2 )
gps$lat <- (as.numeric(gps$dd2) + (as.numeric(gps$mm2)/60))
gps <- gps[,c("course", "speed", "day", "Time", "lon", "lat")]

gps$speed <- as.numeric(gps$speed)
gps$course <- as.numeric(gps$course)

gps$seq <- c(1:nrow(gps))
gps[is.na(gps$lon),]$lon <- 0
gps[is.na(gps$lat),]$lat <- 0

gps$way <- "come"
gps[c(1:520),]$way <- "go"
gps$way <- as.factor(gps$way)

map <- get_map(c(lon = -84.384, lat = 33.776), zoom = 16, source = "stamen", maptype = "toner")
mapPoints <- ggmap(map) + geom_point(aes(x = lon, y = lat, colour=way, size = scale(speed)), data = gps, alpha = 0.40) + labs(colour="Way", size="Speed")
mapPoints

map <- get_map(c(lon = -84.387, lat = 33.777), zoom = 18, source = "stamen", maptype = "toner")
mapPoints <- ggmap(map) +geom_point(aes(x = lon, y = lat, colour=way), data = gps[257:257,], alpha = 0.8, size = 0.5)
mapPoints

# 257 is the reference point to sync between GoPro video and the GPS data
gps$video_time <- as.POSIXct("00:01:16", origin="1970-01-01", format = "%H:%M:%S")

for (i in c(1:nrow(gps))){
  gps[i,]$video_time <- gps[257,]$video_time - 257 + i
}

map <- get_map(c(lon = -84.380, lat = 33.777), zoom = 17, source = "stamen", maptype = "toner")
mapPoints <- ggmap(map) +geom_point(aes(x = lon, y = lat, colour=way), data = gps[555:560,], alpha = 0.8, size = 0.5)
mapPoints

gps[c(487:nrow(gps)),]$video_time <- as.POSIXct("00:00:02", origin="1970-01-01", format = "%H:%M:%S")

for (i in c(487:nrow(gps))){
  gps[i,]$video_time <- gps[555,]$video_time - 555 + i
}

# joining proximiyt values
prox <- read_delim("signatures/Noel/170720_proximity_noel.csv", delim = ",", col_names = T)
prox$Time <- prox$Time -  (3600 * 4)
prox_sum <- prox %>% dplyr::group_by(Time) %>% summarise(USRight=mean(USRight),USLeft=mean(USLeft),USRear=mean(USRear),LidarRight=mean(LidarRight),LidarLeft=mean(LidarLeft), CO=mean(CO, na.rm=T), SO=mean(SO, na.rm=T), O3=mean(O3, na.rm=T), NO=mean(NO, na.rm=T), P10=mean(P10, na.rm=T), P25=mean(P25, na.rm=T) )

gps <- gps %>% left_join(prox_sum, by=c("Time"))
write.table(gps, "signatures/Noel/prox_gps_join.csv", row.names=F, col.names=T, sep=",")

```


# 7/21/2017 Jeremy's
```{r}
gps <- fromJSON(txt= "Jeremy/210717_gps_data.json" )
gps <- as.data.frame(gps["results"])

colnames(gps) <- c("lon", "course","lat","speed","day","utc_time")
gps$utc_time <- as.character(gps$utc_time)
gps["time"] <- as.POSIXct(gps$utc_time, origin="1970-01-01", format = "%H%M%S")
gps$time <- gps$time - (3600 * 4)

gps <- gps %>% separate(lon, into = c("dd","mm"), sep=3 )
gps$lon <- -(as.numeric(gps$dd) + (as.numeric(gps$mm)/60))
gps <- gps %>% separate(lat, into = c("dd2","mm2"), sep=2 )
gps$lat <- (as.numeric(gps$dd2) + (as.numeric(gps$mm2)/60))
gps <- gps[,c("course", "speed", "day", "time", "lon", "lat")]

gps$speed <- as.numeric(gps$speed)
gps$course <- as.numeric(gps$course)

gps$seq <- c(1:nrow(gps))
gps[is.na(gps$lon),]$lon <- 0
gps[is.na(gps$lat),]$lat <- 0

gps$way <- "come"
gps[c(1:416),]$way <- "go"
gps$way <- as.factor(gps$way)

write.table(gps, "Jeremy/210717_gps.csv", row.names=F, col.names=T, sep=",")

map <- get_map(c(lon = -84.397, lat = 33.780), zoom = 16, source = "stamen", maptype = "toner")
mapPoints <- ggmap(map) + geom_point(aes(x = lon, y = lat, colour=way), data = gps, alpha = 0.9, size = 0.5) + labs(colour="Way", size="Speed") + ggtitle("Jeremy, 0721")
mapPoints

map <- get_map(c(lon = -84.400, lat = 33.782), zoom = 17, source = "stamen", maptype = "toner")
mapPoints <- ggmap(map) +geom_point(aes(x = lon, y = lat, colour=way), data = gps[312:314,], alpha = 0.8, size = 0.5)
mapPoints

# 312 is the reference point to sync between GoPro video and the GPS data
gps$video_time <- as.POSIXct("00:03:01", origin="1970-01-01", format = "%H:%M:%S")

for (i in c(1:nrow(gps))){
  gps[i,]$video_time <- gps[312,]$video_time - 312 + i
}


# joining proximiy values
prox <- fromJSON(txt= "Jeremy/210717_proximity.json" )
prox <- as.data.frame(prox["results"])
prox$USLeft <- prox$results.data$USLeft
prox$USRight <- prox$results.data$USRight
prox$USRear <- prox$results.data$USRear
prox$LidarLeft <- prox$results.data$LidarLeft
prox$LidarRight<- prox$results.data$LidarRight
prox$O3 <- prox$results.data$O3
prox$SO <- prox$results.data$SO
prox$NO <- prox$results.data$NO
prox$CO <- prox$results.data$CO
prox$P10 <- prox$results.data$P10
prox$P25 <- prox$results.data$P25
prox <- prox[,-3] # removing the nexted "data" column

prox <- prox %>% separate(results.timestamp, into = c("date","time"), sep=6 )
prox["time"] <- as.POSIXct(prox$time, origin="1970-01-01", format = "%H%M%S")
prox$time <- prox$time -  (3600 * 4)

prox$USLeft <- as.numeric(prox$USLeft)
prox$USRight <- as.numeric(prox$USRight)
prox$USRear <- as.numeric(prox$USRear)
prox$LidarLeft <- as.numeric(prox$LidarLeft)
prox$LidarRight <- as.numeric(prox$LidarRight)
prox$P10 <- as.numeric(prox$P10)
prox$P25 <- as.numeric(prox$P25)
prox$O3 <- as.numeric(prox$O3)
prox$CO <- as.numeric(prox$CO)
prox$SO <- as.numeric(prox$SO)
prox$NO <- as.numeric(prox$NO)


prox_sum <- prox %>% dplyr::group_by(time) %>% summarise(USRight=mean(USRight),USLeft=mean(USLeft),USRear=mean(USRear),LidarRight=mean(LidarRight),LidarLeft=mean(LidarLeft), CO=mean(CO, na.rm=T), SO=mean(SO, na.rm=T), O3=mean(O3, na.rm=T), NO=mean(NO, na.rm=T), P10=mean(P10, na.rm=T), P25=mean(P25, na.rm=T) )

gps <- gps %>% left_join(prox_sum, by=c("time"))
write.table(gps, "Jeremy/prox_gps_join.csv", row.names=F, col.names=T, sep=",")

```


# 7/20/2017 Mariam's
```{r}
gps <- read_delim("Mariam/200717_gps_data.csv", delim = ",", col_names = T)

gps$utc_time <- as.character(gps$utc_time)
gps$time <- str_pad(gps$utc_time, width=6, side="left", pad="0")
gps["time"] <- as.POSIXct(gps$time, origin="1970-01-01", format = "%H%M%S")
gps$time <- gps$time - (3600 * 4)

gps <- gps %>% separate(long, into = c("dd","mm"), sep=3 )
gps$lon <- -(as.numeric(gps$dd) + (as.numeric(gps$mm)/60))
gps <- gps %>% separate(lat, into = c("dd2","mm2"), sep=2 )
gps$lat <- (as.numeric(gps$dd2) + (as.numeric(gps$mm2)/60))
gps <- gps[,c("course", "speed", "day", "time", "lon", "lat")]

gps$speed <- as.numeric(gps$speed)
gps$course <- as.numeric(gps$course)

gps$seq <- c(1:nrow(gps))
gps[is.na(gps$lon),]$lon <- 0
gps[is.na(gps$lat),]$lat <- 0

gps$way <- "second_ride"
gps[c(1:1301),]$way <- "first_ride"
gps$way <- as.factor(gps$way)

map <- get_map(c(lon = -84.397, lat = 33.760), zoom = 12, source = "stamen", maptype = "toner")
mapPoints <- ggmap(map) + geom_point(aes(x = lon, y = lat, colour=way), data = gps, alpha = 0.9, size = 0.5) + labs(colour="Way", size="Speed") + ggtitle("Mariam, 0720")
mapPoints

#first ride
map <- get_map(c(lon = -84.390, lat = 33.764), zoom = 14, source = "stamen", maptype = "toner")
mapPoints <- ggmap(map) + geom_point(aes(x = lon, y = lat, colour=way), data = gps, alpha = 0.9, size = 0.5) + labs(colour="Way", size="Speed") + ggtitle("Mariam, 0720, First Ride")
mapPoints

#second ride
map <- get_map(c(lon = -84.305, lat = 33.783), zoom = 15, source = "stamen", maptype = "toner")
mapPoints <- ggmap(map) + geom_point(aes(x = lon, y = lat, colour=way), data = gps, alpha = 0.9, size = 0.5) + labs(colour="Way", size="Speed") + ggtitle("Mariam, 0720, Second Riding")
mapPoints


# joining proximiy values
prox <- read_delim("Mariam/200717_proximity.csv", delim = ",", col_names = T)
attr(prox$time, "tzone") <- "EST5EDT"

prox_sum <- prox %>% dplyr::group_by(time) %>% summarise(USRight=mean(USRight, na.rm=T),USLeft=mean(USLeft, na.rm=T),USRear=mean(USRear, na.rm=T),LidarRight=mean(LidarRight, na.rm=T),LidarLeft=mean(LidarLeft, na.rm=T), CO=mean(CO, na.rm=T), SO=mean(SO, na.rm=T), O3=mean(O3, na.rm=T), NO=mean(NO, na.rm=T), P10=mean(P10, na.rm=T), P25=mean(P25, na.rm=T) )

gps <- gps %>% left_join(prox_sum, by=c("time"))
write.table(gps, "Jeremy/prox_gps_join.csv", row.names=F, col.names=T, sep=",")

```








# Arduino Data
```{r}
setwd("/Users/myeong/git/Atl_DSSG/Cycle-Atlanta-SLaB/Data/sample_data/")
ard <- fromJSON(txt= "270617_arduino_data.json" )
ard <- as.data.frame(ard["results"])

colnames(ard) <- c("LidarLeft", "USLeft", "LidarRight", "USRear", "Time", "USRight", "CO", "NO2", "P10", "P25", "SO2", "O3")
ard <- ard %>% separate(Time, into = c("date","time"), sep=6 )
ard$time <- as.numeric(ard$time)
ard$time <- ard$time - 40000

for (i in 1:ncol(ard)){
  ard[,i] <- as.numeric(ard[,i])  
}
ard$seq <- c(1:nrow(ard))

ggplot(ard, aes(x = seq)) +
  geom_line(aes(y = LidarRight), colour="blue") + 
  geom_point(aes(y = LidarRight), colour="blue") + 
  geom_line(aes(y = USRight), colour="red") +
  geom_point(aes(y = USRight), colour="red") +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Magnitude") + 
  xlab("Time (sec)") + xlim(113, 162) + ggtitle("Time-Series Distances for the Right-Side Lidar and Sonar")

summary(lm(LidarLeft ~ USLeft, data=ard))
summary(lm(LidarRight ~ USRight, data=ard))

ggplot(ard, aes(x = seq)) +
  geom_line(aes(y = LidarLeft), colour="blue") + 
  geom_point(aes(y = LidarLeft), colour="blue") + 
  geom_line(aes(y = USLeft), colour="red") +
  geom_point(aes(y = USLeft), colour="red") +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Magnitude") + 
  xlab("Time (sec)") +  xlim(113, 162) +ggtitle("Time-Series Distances for the Left-Side Lidar and Sonar")

ggplot(ard, aes(x = seq)) +
  geom_line(aes(y = USRear), colour="red") +
  geom_point(aes(y = USRear), colour="red") +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Magnitude") + 
  xlab("Time (sec)") +  xlim(113, 162) +ggtitle("Time-Series Distance for the Rear Sonar")

gas <- ard[,c("seq","CO","SO2","O3","NO2")]
gas <- gas[complete.cases(gas),]

ggplot(gas, aes(x = seq)) +
  geom_line(aes(y = CO), colour="red") +
  geom_point(aes(y = CO), colour="red") +
  geom_line(aes(y = NO2), colour="blue") +
  geom_point(aes(y = NO2), colour="blue") +
  geom_line(aes(y = SO2), colour="green") +
  geom_point(aes(y = SO2), colour="green") +
  geom_line(aes(y = O3), colour="violet") +
  geom_point(aes(y = O3), colour="violet") +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Magnitude") + 
  xlab("Time (sec)") +  xlim(113, 162) +ggtitle("Time-Series Gas Sensor Values")

```

# Inertial
```{r}
setwd("/Users/myeong/git/Atl_DSSG/Cycle-Atlanta-SLaB/Data/sample_data/")
imu <- fromJSON(txt= "270617_imu.json" )
imu <- as.data.frame(imu["results"])
times <- imu$results.timestamp
imu <- as.data.frame(imu$results.data)
imu$time <- times
imu$seq <- c(1:nrow(imu))

imu$gyro <- apply(imu[,c("gyro_x","gyro_y","gyro_z")], 1, mean )

ggplot(imu, aes(x = seq)) +
  geom_line(aes(y = gyro), colour="red") +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Magnitude") + 
  xlab("Time (sec)")  +ggtitle("Time-Series Gyroscope Values")

imu$accel_z <- abs(imu$accel_z)

ggplot(imu, aes(x = seq)) +
#   geom_point(aes(y = gyro), colour="red") +
  geom_line(aes(y = accel_z), colour="blue") +
#   geom_point(aes(y = accel_z), colour="blue") +
  theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Magnitude") + 
  xlab("Time (sec)")   +ggtitle("Time-Series Accelerometer Values")

summary(lm(roll~accel_z, data=imu))

```


