---
title: "Cycle Data Preprocessing"
author: "Myeong Lee"
date: "7/22/2017"
output: html_document
---

This script preprocess the cycle sensors data so that they can be used as features and classifiers.

```{r}
library(jsonlite)
library(readr)
library(dplyr)
library(sp)
library(ggplot2)
library(ggmap)
library(dplyr)
library(tidyr)
library(geosphere)
library(scales)

setwd("/Users/myeong/git/Atl_DSSG/Cycle-Atlanta-SLaB/DSSG2017_data/sample_data/Javier/")

multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

gps <- read_delim("0722_prox_gps_join.csv", delim = ",", col_names = T)
prox <- read_delim("220717_prox.csv", delim = ",", col_names = T)
gps$id <- c(1:nrow(gps))
prox$id <- c(1:nrow(prox))

first <- gps[c(1:468),c("time", "lon", "lat", "video_time", "way", "speed", "LidarRight", "LidarLeft")]

LR <- ggplot(first, aes(x = video_time, y = LidarRight)) +
      geom_line() +
      geom_point(size = 0.5, color="red")  + 
      ylim(c(0,4000)) + scale_x_datetime(breaks=date_breaks("30 sec"), labels=date_format("%H:%M:%S")) +
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Distance (cm)") + 
      xlab("Video Time")  + ggtitle("Lidar Right (Video_time)") 

LL <- ggplot(first, aes(x = video_time, y = LidarLeft)) +
      geom_line() +
      geom_point( size = 0.5, color="red")  +
      ylim(c(0,4000))  + scale_x_datetime(breaks=date_breaks("30 sec"), labels=date_format("%H:%M:%S")) +
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Distance (cm)") + 
      xlab("Video Time")  + ggtitle("Lidar Left (Video_time)")

multiplot(LR, LL, cols=1)



# Actual riding begins at 0:02:00 in the video.
# Until 2017-07-22 03:54:38
first <- gps[c(139:468),c("time", "lon", "lat", "video_time", "way", "speed")]
second <- gps[c(474:nrow(gps)),c("time", "lon", "lat", "video_time", "way", "speed")]

prox_first <- prox[c(723:1825),]
prox_second <- prox[c(1826:nrow(prox)),]

first_join <- prox_first %>% left_join(first, by=c("time"))

first_join$seq <- paste(as.character(first_join$video_time), as.character(first_join$id), sep="_")
first_join$seq <- as.factor(first_join$seq)

#Video-time-based high-resolution graph
LR <- ggplot(first_join, aes(x = video_time)) +
      geom_line(aes(y = LidarRight), color="black") +
      geom_point(aes(y = LidarRight),size = 0.5, color="red")  +      
      ylim(c(0,9000))  + 
      scale_x_datetime(breaks=date_breaks("30 sec"), labels=date_format("%H:%M:%S")) +      
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Distance (cm)") + 
      xlab("Dummy Time (x200ms)")  + ggtitle("Lidar Right (Raw Data)") 

LL <- ggplot(first_join, aes(x = video_time)) +
      geom_line(aes(y = LidarLeft), color="black") +
      geom_point(aes(y = LidarLeft),size = 0.5, color="red")  +       
      ylim(c(0,9000))  + 
      scale_x_datetime(breaks=date_breaks("10 sec"), labels=date_format("%H:%M:%S")) +
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Distance (cm)") + 
      xlab("Dummy Time (x200ms)")  + ggtitle("Lidar Left (Raw Data)")

multiplot(LR, LL, cols=1)

# Close-up
LR <- ggplot(first_join[c(500:550),], aes(x = id)) +
      geom_line(aes(y = LidarRight), color="black") +
      geom_point(aes(y = LidarRight),size = 0.5, color="red")  + 
      geom_line(aes(y=100*(speed)), color="blue") + 
      geom_point(aes(y=100*(speed)),size = 0.5, color="blue")  +
      ylim(c(0,3000))  + 
#       scale_x_datetime(breaks=date_breaks("30 sec"), labels=date_format("%H:%M:%S")) +      
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Distance (cm)") + 
      xlab("Dummy Time (x200ms)")  + ggtitle("Lidar Right (Raw Data)") 

LL <- ggplot(first_join[c(500:550),], aes(x = id)) +
      geom_line(aes(y = LidarLeft), color="black") +
      geom_point(aes(y = LidarLeft),size = 0.5, color="red")  + 
      geom_line(aes(y=100*(speed)), color="blue") + 
      geom_point(aes(y=100*(speed)),size = 0.5, color="blue")  +
      ylim(c(0,3000))  + 
#       scale_x_datetime(breaks=date_breaks("10 sec"), labels=date_format("%H:%M:%S")) +
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Distance (cm)") + 
      xlab("Dummy Time (x200ms)")  + ggtitle("Lidar Left (Raw Data)")

multiplot(LR, LL, cols=1)

```


# Time domain to Distance domain (Value-lagging)
```{r}
first_join$dist <- 0
time_interval <- 0.2994975 #seconds

# distance intervals (just for reference)
dists <- as.vector(c(0))

for (i in c(1:nrow(first_join))){
  if (i==nrow(first_join)) break
  sp <- first_join[i,]$speed * 0.514444444 # changing the speed to meters/sec
  first_join[i+1,]$dist <- first_join[i,]$dist + (sp * time_interval)
  dists[i] <- (sp * time_interval)
}

d <- density(dists)
plot(d, main="Kernel Density of Distances per Lidar Reading")
polygon(d, col="violet")

#Distance-based plot
LR <- ggplot(first_join, aes(x = dist)) +
      geom_line(aes(y = LidarRight), color="black") +
      geom_point(aes(y = LidarRight),size = 0.5, color="red")  +      
      ylim(c(0,9000))  +       
      scale_x_continuous(breaks =seq(0, 1550, 50)) + 
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Lidar Distance (cm)") + 
      xlab("Distance Traveled (m)")  + ggtitle("Lidar Right (Distance-based)") 

LL <- ggplot(first_join, aes(x = dist)) +
      geom_line(aes(y = LidarLeft), color="black") +
      geom_point(aes(y = LidarLeft),size = 0.5, color="red")  +       
      ylim(c(0,9000))  +       
      scale_x_continuous(breaks = seq(0, 1550, 50)) + 
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Lidar Distance (cm)") + 
      xlab("Distance Traveled (m)")  + ggtitle("Lidar Left (Distance-based)")

multiplot(LR, LL, cols=1)


# Close-up
LR <- ggplot(first_join[c(600:650),], aes(x = dist)) +
      geom_line(aes(y = LidarRight), color="black") +
      geom_point(aes(y = LidarRight),size = 1, color="red")  +      
      ylim(c(0,2900))  +       
      scale_x_continuous(breaks =seq(775, 835, 5)) + 
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Lidar Distance (cm)") + 
      xlab("Distance Traveled (m)")  + ggtitle("Lidar Right (Distance-based), Close-up") 

LL <- ggplot(first_join[c(600:650),], aes(x = dist)) +
      geom_line(aes(y = LidarLeft), color="black") +
      geom_point(aes(y = LidarLeft),size = 1, color="red")  +       
      ylim(c(0,2900))  +       
      scale_x_continuous(breaks = seq(775, 835, 5)) + 
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Lidar Distance (cm)") + 
      xlab("Distance Traveled (m)")  + ggtitle("Lidar Left (Distance-based), Close-up")

multiplot(LR, LL, cols=1)

# Saving the first_join
write.table(first_join, "220717_first_part_distance_based.csv", row.names=F, col.names=T, sep=",")

```


# Naive Interpolation
```{r}

gps <- read_delim("220717_first_part_distance_based.csv", delim = ",", col_names = T)
first_join$way <- as.factor(first_join$way)

prevL <- 0
prevR <- 0

first_join$adjustedLidarLeft <- 0
first_join$adjustedLidarRight <- 0

for (i in c(1:nrow(first_join))){
  if (i==1){
    prevL <- first_join[i,]$LidarLeft
    prevR <- first_join[i,]$LidarRight
    first_join[i,]$adjustedLidarLeft <- prevL
    first_join[i,]$adjustedLidarRight <- prevR
    next
  }
  
  if (first_join[i,]$LidarLeft <= 1) {
    first_join[i,]$adjustedLidarLeft <- prevL    
  } else {    
    prevL <- first_join[i,]$LidarLeft
    first_join[i,]$adjustedLidarLeft <- prevL
  }
  
  if (first_join[i,]$LidarRight <= 1){
    first_join[i,]$adjustedLidarRight <- prevR
  } else {
    prevR <- first_join[i,]$LidarRight
    first_join[i,]$adjustedLidarRight <- prevR
  }
  
}


#Distance-based plot
LR <- ggplot(first_join, aes(x = dist)) +
      geom_line(aes(y = LidarRight), color="black") +
      geom_point(aes(y = LidarRight),size = 0.5, color="red")  +      
      geom_line(aes(y = adjustedLidarRight), color="blue") +
      geom_point(aes(y = adjustedLidarRight), size = 0.5, color="blue")  +   
      ylim(c(0,9000))  +       
      scale_x_continuous(breaks =seq(0, 1550, 50)) + 
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Lidar Distance (cm)") + 
      xlab("Distance Traveled (m)")  + ggtitle("Lidar Right (Distance-based)") 

LL <- ggplot(first_join, aes(x = dist)) +
      geom_line(aes(y = LidarLeft), color="black") +
      geom_point(aes(y = LidarLeft),size = 0.5, color="red")  +    
      geom_line(aes(y = adjustedLidarLeft), color="blue") +
      geom_point(aes(y = adjustedLidarLeft), size = 0.5, color="blue")  +  
      ylim(c(0,9000))  +       
      scale_x_continuous(breaks = seq(0, 1550, 50)) + 
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Lidar Distance (cm)") + 
      xlab("Distance Traveled (m)")  + ggtitle("Lidar Left (Distance-based)")

multiplot(LR, LL, cols=1)


# Close-up (car passing-by)
LR <- ggplot(first_join[c(370:410),], aes(x = dist)) +
      geom_line(aes(y = LidarRight), color="black") +
      geom_point(aes(y = LidarRight),size = 2, color="red")  +  
      geom_line(aes(y = adjustedLidarRight), color="blue") +
      geom_point(aes(y = adjustedLidarRight), size = 1, color="blue")  +   
      ylim(c(0,3200))  +       
      scale_x_continuous(breaks =seq(360, 510, 5)) + 
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Lidar Distance (cm)") + 
      xlab("Distance Traveled (m)")  + ggtitle("Lidar Right (Distance-based), Close-up") 

LL <- ggplot(first_join[c(370:410),], aes(x = dist)) +
      geom_line(aes(y = LidarLeft), color="black") +
      geom_point(aes(y = LidarLeft),size = 2, color="red")  +   
      geom_line(aes(y = adjustedLidarLeft), color="blue") +
      geom_point(aes(y = adjustedLidarLeft), size = 1, color="blue")  +  
      ylim(c(0,3200))  +       
      scale_x_continuous(breaks = seq(360, 510, 5)) + 
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Lidar Distance (cm)") + 
      xlab("Distance Traveled (m)")  + ggtitle("Lidar Left (Distance-based), Close-up")

multiplot(LR, LL, cols=1)

write.table(first_join, "220717_first_part_interpolated_lidars.csv", row.names=F, col.names=T, sep=",")
```


# Adjusting data points into the regular grid (1m): Resampling
```{r}
# Given the median value of distances per lidar reading (=1.29 m), we set 1m as a unit to generate a regular-grid distance-based data
first_regular_dist <- as.data.frame(matrix(ncol=16, nrow = as.integer(max(first_join$dist))))
colnames(first_regular_dist) <- c("dist", "LidarLeft", "LidarRight", "time", "video_time", "USLeft", "USRight", "USRear", "CO", "SO", "NO", "O3", "P10", "P25", "lon", "lat")
first_regular_dist$video_time <- as.POSIXct(first_regular_dist$video_time)
attr(first_regular_dist$video_time, "tzone") <- "UTC"
first_regular_dist$time <- as.POSIXct(first_regular_dist$time)
attr(first_regular_dist$time, "tzone") <- "UTC"
resolution <- 10

for (i in c(1:nrow(first_regular_dist))){    
  print(i)
  if (max(first_join$dist) < i-1) {
    break
  }
  first_regular_dist[i,]$dist <- i - 1  
  index <- which.min(abs(first_join$dist - i + 1))
  
  if (first_join[index,]$dist <= i-1) {
    lidar_left <- (((i - 1 - first_join[index,]$dist)*(first_join[index+1,]$adjustedLidarLeft - first_join[index,]$adjustedLidarLeft)) / (first_join[index+1,]$dist - first_join[index,]$dist)) + first_join[index,]$adjustedLidarLeft
    lidar_right <- (((i - 1 - first_join[index,]$dist)*(first_join[index+1,]$adjustedLidarRight - first_join[index,]$adjustedLidarRight)) / (first_join[index+1,]$dist - first_join[index,]$dist)) + first_join[index,]$adjustedLidarRight    
    us_left <- (((i - 1 - first_join[index,]$dist)*(first_join[index+1,]$USLeft - first_join[index,]$USLeft)) / (first_join[index+1,]$dist - first_join[index,]$dist)) + first_join[index,]$USLeft
    us_right <- (((i - 1 - first_join[index,]$dist)*(first_join[index+1,]$USRight - first_join[index,]$USRight)) / (first_join[index+1,]$dist - first_join[index,]$dist)) + first_join[index,]$USRight
    us_rear <- (((i - 1 - first_join[index,]$dist)*(first_join[index+1,]$USRear - first_join[index,]$USRear)) / (first_join[index+1,]$dist - first_join[index,]$dist)) + first_join[index,]$USRear
    
    dist_rate <- resolution * (i - 1 - first_join[index,]$dist) / (first_join[index+1,]$dist - first_join[index,]$dist)
    dist_rate <- as.integer(dist_rate)
    points <- gcIntermediate(first_join[index,c("lon","lat")], first_join[index+1,c("lon","lat")], resolution-1)
        
    if (dist_rate == 0 | nrow(points) == 1){
      first_regular_dist[i,]$lat <- first_join[index,]$lat
      first_regular_dist[i,]$lon <- first_join[index,]$lon
    } else if (dist_rate == resolution) {
      first_regular_dist[i,]$lat <- first_join[index+1,]$lat
      first_regular_dist[i,]$lon <- first_join[index+1,]$lon
    } else {      
      first_regular_dist[i,]$lat <- points[dist_rate,2]
      first_regular_dist[i,]$lon <- points[dist_rate,1]
    }    
    
  } else {
    lidar_left <- (((i - 1 - first_join[index-1,]$dist)*(first_join[index,]$adjustedLidarLeft - first_join[index-1,]$adjustedLidarLeft)) / (first_join[index,]$dist - first_join[index-1,]$dist)) + first_join[index-1,]$adjustedLidarLeft
    lidar_right <- (((i - 1 - first_join[index-1,]$dist)*(first_join[index,]$adjustedLidarRight - first_join[index-1,]$adjustedLidarRight)) / (first_join[index,]$dist - first_join[index-1,]$dist)) + first_join[index-1,]$adjustedLidarRight
    us_left <- (((i - 1 - first_join[index-1,]$dist)*(first_join[index,]$USLeft - first_join[index-1,]$USLeft)) / (first_join[index,]$dist - first_join[index-1,]$dist)) + first_join[index-1,]$USLeft
    us_right <- (((i - 1 - first_join[index-1,]$dist)*(first_join[index,]$USRight - first_join[index-1,]$USRight)) / (first_join[index,]$dist - first_join[index-1,]$dist)) + first_join[index-1,]$USRight
    us_rear <- (((i - 1 - first_join[index-1,]$dist)*(first_join[index,]$USRear - first_join[index-1,]$USRear)) / (first_join[index,]$dist - first_join[index-1,]$dist)) + first_join[index-1,]$USRear
    
    dist_rate <- resolution * (i - 1 - first_join[index-1,]$dist) / (first_join[index,]$dist - first_join[index-1,]$dist)
    dist_rate <- as.integer(dist_rate)    
    points <- gcIntermediate(first_join[index-1,c("lon","lat")], first_join[index,c("lon","lat")], resolution-1)
    
    if (dist_rate == 0 | nrow(points) == 1){
      first_regular_dist[i,]$lat <- first_join[index-1,]$lat
      first_regular_dist[i,]$lon <- first_join[index-1,]$lon
    } else if (dist_rate == resolution) {
      first_regular_dist[i,]$lat <- first_join[index,]$lat
      first_regular_dist[i,]$lon <- first_join[index,]$lon
    } else {      
      first_regular_dist[i,]$lat <- points[dist_rate,2]
      first_regular_dist[i,]$lon <- points[dist_rate,1]
    }
  }
  
  first_regular_dist[i,]$LidarLeft <- lidar_left
  first_regular_dist[i,]$LidarRight <- lidar_right    
  first_regular_dist[i,]$USLeft <- us_left
  first_regular_dist[i,]$USRight <- us_right
  first_regular_dist[i,]$USRear <- us_rear
  first_regular_dist[i,]$CO <- first_join[index,]$CO  
  first_regular_dist[i,]$SO <- first_join[index,]$SO  
  first_regular_dist[i,]$O3 <- first_join[index,]$O3  
  first_regular_dist[i,]$NO <- first_join[index,]$NO  
  first_regular_dist[i,]$P10 <- first_join[index,]$P10  
  first_regular_dist[i,]$P25 <- first_join[index,]$P25  
  first_regular_dist[i,]$time <- first_join[index,]$time  
  first_regular_dist[i,]$video_time <- first_join[index,]$video_time
  
}

first_regular_dist <- first_regular_dist[!is.na(first_regular_dist$lon),]

#### gcIntermediate function test
# inter <- gcIntermediate(first_join[27,c("lon","lat")],first_join[28,c("lon","lat")], 10)
# inter <- rbind(first_join[5,c("lon","lat")], inter)
# inter <- rbind(inter, first_join[26,c("lon","lat")])
# inter$id <- c(1:nrow(inter))
# 
# map <- get_map(inter[3,], zoom = 18, source = "stamen", maptype = "toner")
# mapPoints <- ggmap(map) + geom_point(aes(x = lon, y = lat, colour=id ), data = inter, alpha = 0.9, size = 0.5) + ggtitle("gcIntermediate Test")
# mapPoints



# Close-up (random segment)
LR <- ggplot(first_join[c(50:100),], aes(x = dist)) +      
      geom_line(aes(y = adjustedLidarRight), color="black") +
      geom_point(aes(y = adjustedLidarRight), size = 1, color="red")  +         
      ylim(c(0,2600))  +       
      scale_x_continuous(breaks =seq(0, 60, 1)) + 
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Lidar Distance (cm)") + 
      xlab("Distance Traveled (m)")  + ggtitle("Lidar Right (Distance-based), Close-up") 

LL <- ggplot(first_regular_dist[c(7:58),], aes(x = dist)) +      
      geom_line(aes(y = LidarRight), color="black") +
      geom_point(aes(y = LidarRight), size = 1, color="red")  +        
      ylim(c(0,2600))  +       
      scale_x_continuous(breaks = seq(0, 60, 1)) + 
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Lidar Distance (cm)") + 
      xlab("Distance Traveled (m)")  + ggtitle("Lidar Right (Re-sampled), Close-up")

multiplot(LR, LL, cols=1)

# Close-up (car passing-by)
LR <- ggplot(first_join[c(370:410),], aes(x = dist)) +      
      geom_line(aes(y = adjustedLidarLeft), color="black") +
      geom_point(aes(y = adjustedLidarLeft), size = 1, color="red")  +         
      ylim(c(0,3300))  +       
      scale_x_continuous(breaks =seq(360, 500, 5)) + 
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Lidar Distance (cm)") + 
      xlab("Distance Traveled (m)")  + ggtitle("Lidar Left (Distance-based), Close-up") 

LL <- ggplot(first_regular_dist[c(364:491),], aes(x = dist)) +      
      geom_line(aes(y = LidarLeft), color="black") +
      geom_point(aes(y = LidarLeft), size = 1, color="red")  +        
      ylim(c(0,3300))  +       
      scale_x_continuous(breaks = seq(360, 500, 5)) + 
      theme_bw() + theme(legend.text=element_text(size=15)) + ylab(label="Lidar Distance (cm)") + 
      xlab("Distance Traveled (m)")  + ggtitle("Lidar Left (Re-sampling), Close-up")

multiplot(LR, LL, cols=1)

classifiers <- c("car", "stop-car", "parallel", "tree", "posts", "trashcan", "wall", "nothing", "people", "bike")

first_regular_dist$classification <- sample(classifiers, nrow(first_regular_dist), replace = T)
write.table(first_regular_dist, "220717_first_part_resampled.csv", row.names=F, col.names=T, sep=",")

```


